#! /usr/bin/env bash

FRAMEWORK_NAME=YouTubeUploaderFramework
IPHONEOS_FRAMEWORK_PATH=./build/Release-iphoneos/${FRAMEWORK_NAME}.framework
IPHONESIMULATOR_FRAMEWORK_PATH=./build/Release-iphonesimulator/${FRAMEWORK_NAME}.framework
UNIVERSAL_PATH=./build/Release-universal/
UNIVERSAL_FRAMEWORK_PATH=${UNIVERSAL_PATH}/${FRAMEWORK_NAME}.framework

xcodebuild -target $FRAMEWORK_NAME -configuration Release -sdk iphoneos

xcodebuild -target $FRAMEWORK_NAME -configuration Release -sdk iphonesimulator

rm -rf $UNIVERSAL_PATH
mkdir $UNIVERSAL_PATH

cp -r  "${IPHONEOS_FRAMEWORK_PATH}" "${UNIVERSAL_FRAMEWORK_PATH}"

lipo "${IPHONEOS_FRAMEWORK_PATH}/${FRAMEWORK_NAME}" "${IPHONESIMULATOR_FRAMEWORK_PATH}/${FRAMEWORK_NAME}" -create -output "${UNIVERSAL_FRAMEWORK_PATH}/${FRAMEWORK_NAME}"
